### ISSUE TITLE
relation to sbitmedia.munin?

### ISSUE THREAD

**Issue by drzraf** [geerlingguy/ansible-role-munin#7]
Hi,

I found this repository while exploring my possible switch from the [sbitmedia.munin](https://github.com/sbitio/ansible-munin) role that I used up to know.
Ansible 2.0 isn't going to be supported there any [time soon](https://github.com/sbitio/ansible-munin/issues/14) [I myself couldn't find any UPGRADE documentation when it comes to internal plugins API]

Since I highly customize munin (master, on one machine) and node (on other ones) and since I use munin-async protocol (ssh-based), I'm not very interested in current ansible-role-munin as it is, but I've two questions anyway:

1° would you accept minimalist (hypothetical) PR of a task file for munin-async setup ?
2° I found munin_plugins [action-plugin](https://github.com/sbitio/ansible-munin) sometimes very useful, do you share this interest? (that would help me figuring out what future to expect / what effort to put into the role I currently use)

**Comment by geerlingguy** [comment]
@drzraf - At this time, I don't want to add that support, as the role is meant to be helpful for smaller munin installations which may not require munin-async support (e.g. I'm using it in many instances where only 1-50 servers are being monitored).

**Comment by drzraf** [comment]
Any thought specifically about the action-plugin thing ?
(cf https://github.com/sbitio/ansible-munin/pull/17)

**Comment by drzraf** [comment]
just a ping about the last comment: would you mind providing the Ansible 2.0 action-plugin in order to write such tasks:
```
- munin_plugin:
  args:
    name: port
    instance: port_http
  notify: restart munin-node
```

# or defining configuration:
```
- name: Munin memcached
  action: munin_plugin
  args:
    instance: multips_memory_memcache
    name: multips_memory
    config: |
      env.names memcached
```

# or defining a wildcard configuration
```
- name: Munin LAMP multips_memory configuration
  action: munin_plugin
  args:
    instance: 'default_memcached_multi_*'
    name: memcached
    config: |
      group www-data
      env.host unix:///var/run/memcached/memcached.sock
```

?

**Comment by geerlingguy** [comment]
I would consider adding support (but note that the examples above would be a bit easier to read if they were all formatted in the normal way, e.g.

```
- munin_plugin:
    name: port
    instance: port_http
  notify: restart munin-node
```
